CREATE TABLE AccountMapping (
  AccountID VARCHAR -- Unique identifier or primary key,
  AccountName VARCHAR -- Name field,
  AccountCode VARCHAR,
  AccountType VARCHAR,
  Remarks VARCHAR
);

CREATE TABLE APVIEW (
  status VARCHAR,
  vendor_name VARCHAR -- Name field,
  bill_id VARCHAR -- Unique identifier or primary key,
  bill_number VARCHAR,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  description VARCHAR -- Description or notes,
  cf_due_amount_1 DECIMAL -- Monetary amount,
  cf_due_amount_2 DECIMAL -- Monetary amount,
  cf_due_amount_3 DECIMAL -- Monetary amount,
  cf_due_amount_4 DECIMAL -- Monetary amount,
  reference_number VARCHAR -- Reference ID or external link,
  due_date DATE -- Date value,
  cf_due_date_2 DATE -- Date value,
  cf_due_date_3 DATE -- Date value,
  cf_due_date_4 DATE -- Date value,
  balance DECIMAL -- Remaining balance,
  total DECIMAL -- Total value,
  disfordisplay VARCHAR,
  item_total INT -- Total value,
  calcaccounttype VARCHAR,
  Amountdue DECIMAL -- Monetary amount,
  AmountThisWeek DECIMAL -- Monetary amount,
  AmountNextWeek DECIMAL -- Monetary amount,
  Outofscope DECIMAL
);

CREATE TABLE BankAccounts (
  account_pk INT,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  account_code VARCHAR,
  currency_id VARCHAR -- Unique identifier or primary key,
  currency_code VARCHAR -- Currency information,
  account_type VARCHAR,
  account_number VARCHAR,
  uncategorized_transactions INT,
  total_unprinted_checks INT -- Total value,
  is_active BIT,
  balance DECIMAL -- Remaining balance,
  bank_balance DECIMAL -- Remaining balance,
  bcy_balance DECIMAL -- Remaining balance,
  bank_name VARCHAR -- Name field,
  routing_number VARCHAR,
  is_primary_account BIT,
  is_paypal_account BIT,
  feeds_last_refresh_date DATETIME -- Date value,
  is_direct_paypal BIT,
  partner_bank_source_formatted VARCHAR,
  partner_bank_source VARCHAR,
  is_beta_feed BIT,
  consent_remaining_days INT,
  is_consent_expired BIT,
  feed_status VARCHAR,
  data_collection_update_date DATETIME -- Date value,
  is_active_change_date DATE -- Date value
);

CREATE TABLE BankTransactionLineItems (
  transaction_pk INT,
  transaction_id VARCHAR -- Unique identifier or primary key,
  from_account_id VARCHAR -- Unique identifier or primary key,
  from_account_name VARCHAR -- Name field,
  payment_mode VARCHAR -- Payment-related field,
  customer_id VARCHAR -- Unique identifier or primary key,
  customer_name VARCHAR -- Name field,
  vendor_id VARCHAR -- Unique identifier or primary key,
  vendor_name VARCHAR -- Name field,
  sub_total DECIMAL -- Total value,
  total DECIMAL -- Total value,
  bcy_total DECIMAL -- Total value
);

CREATE TABLE BankTransactions (
  transaction_pk INT,
  transaction_id VARCHAR -- Unique identifier or primary key,
  date DATE -- Date value,
  amount DECIMAL -- Monetary amount,
  transaction_type VARCHAR,
  status VARCHAR,
  source VARCHAR,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  account_type VARCHAR,
  price_precision INT,
  customer_id VARCHAR -- Unique identifier or primary key,
  payee VARCHAR,
  is_paid_via_print_check BIT -- Unique identifier or primary key,
  description VARCHAR -- Description or notes,
  currency_id VARCHAR -- Unique identifier or primary key,
  currency_code VARCHAR -- Currency information,
  currency_symbol VARCHAR -- Currency information,
  debit_or_credit VARCHAR,
  offset_account_name VARCHAR -- Name field,
  is_offsetaccount_matched BIT,
  reference_number VARCHAR -- Reference ID or external link,
  imported_transaction_id VARCHAR -- Unique identifier or primary key,
  is_rule_exist BIT,
  rule_details NVARCHAR,
  data_collection_update_date DATETIME -- Date value
);

CREATE TABLE BILL_SO_OLD (
  id INT -- Unique identifier or primary key,
  bill_id VARCHAR -- Unique identifier or primary key,
  SO_reference VARCHAR -- Reference ID or external link,
  delete_ind BIT,
  delete_date DATETIME -- Date value
);

CREATE TABLE BillDetails (
  bill_pk INT,
  bill_id VARCHAR -- Unique identifier or primary key,
  vendor_id VARCHAR -- Unique identifier or primary key,
  vendor_name VARCHAR -- Name field,
  vat_treatment VARCHAR,
  vat_reg_no VARCHAR,
  source_of_supply VARCHAR,
  destination_of_supply VARCHAR,
  place_of_supply VARCHAR,
  permit_number VARCHAR,
  gst_no VARCHAR,
  gst_treatment VARCHAR,
  tax_treatment VARCHAR,
  is_pre_gst BIT,
  pricebook_id VARCHAR -- Unique identifier or primary key,
  pricebook_name VARCHAR -- Name field,
  is_reverse_charge_applied BIT,
  unused_credits_payable_amount DECIMAL -- Monetary amount,
  status VARCHAR,
  bill_number VARCHAR,
  date DATE -- Date value,
  due_date DATE -- Date value,
  payment_terms INT -- Payment-related field,
  payment_terms_label VARCHAR -- Payment-related field,
  reference_number VARCHAR -- Reference ID or external link,
  currency_id VARCHAR -- Unique identifier or primary key,
  currency_code VARCHAR -- Currency information,
  exchange_rate DECIMAL -- Rate or percentage,
  adjustment DECIMAL,
  adjustment_description VARCHAR -- Description or notes,
  is_tds_applied BIT,
  is_item_level_tax_calc BIT,
  is_inclusive_tax BIT,
  filed_in_vat_return_id VARCHAR -- Unique identifier or primary key,
  filed_in_vat_return_name VARCHAR -- Name field,
  filed_in_vat_return_type VARCHAR,
  is_abn_quoted VARCHAR,
  sub_total DECIMAL -- Total value,
  tax_total DECIMAL -- Total value,
  total DECIMAL -- Total value,
  payment_made DECIMAL -- Payment-related field,
  vendor_credits_applied DECIMAL -- Related to vendor,
  is_line_item_invoiced BIT -- Invoice-related field,
  open_purchaseorders_count INT,
  notes VARCHAR,
  terms VARCHAR,
  attachment_name VARCHAR -- Name field,
  documents NVARCHAR,
  custom_fields NVARCHAR,
  taxes NVARCHAR,
  vendor_credits NVARCHAR -- Related to vendor,
  billing_address NVARCHAR -- Address info,
  payments NVARCHAR -- Payment-related field,
  data_collection_update_date DATETIME -- Date value,
  payment_expected_date VARCHAR -- Date value,
  recurring_bill_id VARCHAR -- Unique identifier or primary key,
  due_by_days VARCHAR,
  due_in_days INT,
  price_precision INT,
  created_time DATETIME -- Record creation time,
  created_by_id VARCHAR -- Unique identifier or primary key,
  last_modified_time DATETIME -- Last modification time,
  reference_id VARCHAR -- Unique identifier or primary key,
  balance DECIMAL -- Remaining balance,
  reverse_charge_vat_summary NVARCHAR,
  purchaseorders NVARCHAR,
  acquisition_vat_summary NVARCHAR,
  delete_ind BIT,
  delete_date DATETIME -- Date value,
  cf_due_date_2 DATE -- Date value,
  cf_due_date_3 DATE -- Date value,
  cf_due_date_4 DATE -- Date value,
  cf_due_amount_1 DECIMAL -- Monetary amount,
  cf_due_amount_2 DECIMAL -- Monetary amount,
  cf_due_amount_3 DECIMAL -- Monetary amount,
  cf_due_amount_4 DECIMAL -- Monetary amount
);

CREATE TABLE BillLineItems (
  line_item_pk INT,
  bill_pk INT,
  bill_id VARCHAR -- Unique identifier or primary key,
  line_item_id VARCHAR -- Unique identifier or primary key,
  purchaseorder_item_id VARCHAR -- Unique identifier or primary key,
  item_id VARCHAR -- Unique identifier or primary key,
  sku VARCHAR -- Stock keeping unit,
  name VARCHAR -- Name field,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  quantity DECIMAL -- Quantity or count,
  rate DECIMAL -- Rate or percentage,
  item_total DECIMAL -- Total value,
  tax_percentage DECIMAL,
  tax_name VARCHAR -- Name field,
  tax_amount DECIMAL -- Monetary amount,
  reverse_charge_tax_percentage DECIMAL,
  reverse_charge_tax_amount DECIMAL -- Monetary amount,
  is_billable BIT,
  image_document_id INT -- Unique identifier or primary key,
  warehouse_id INT -- Unique identifier or primary key,
  warehouse_name VARCHAR -- Name field,
  reverse_charge_tax_id VARCHAR -- Unique identifier or primary key,
  reverse_charge_tax_name VARCHAR -- Name field,
  description VARCHAR -- Description or notes,
  bcy_rate DECIMAL -- Rate or percentage,
  tags NVARCHAR,
  tax_id VARCHAR -- Unique identifier or primary key,
  tds_tax_id VARCHAR -- Unique identifier or primary key,
  tax_treatment_code VARCHAR,
  tax_exemption_id VARCHAR -- Unique identifier or primary key,
  tax_exemption_code VARCHAR,
  item_total_inclusive_of_tax DECIMAL -- Total value,
  item_order INT,
  unit VARCHAR,
  product_type VARCHAR,
  hsn_or_sac VARCHAR,
  acquisition_vat_id VARCHAR -- Unique identifier or primary key,
  acquisition_vat_name VARCHAR -- Name field,
  acquisition_vat_percentage DECIMAL,
  acquisition_vat_amount DECIMAL -- Monetary amount,
  reverse_charge_vat_id VARCHAR -- Unique identifier or primary key,
  reverse_charge_vat_name VARCHAR -- Name field,
  reverse_charge_vat_percentage DECIMAL,
  reverse_charge_vat_amount DECIMAL -- Monetary amount,
  customer_id VARCHAR -- Unique identifier or primary key,
  customer_name VARCHAR -- Name field,
  project_id VARCHAR -- Unique identifier or primary key,
  project_name VARCHAR -- Name field,
  invoice_id VARCHAR -- Unique identifier or primary key,
  invoice_number VARCHAR -- Invoice-related field,
  item_custom_fields NVARCHAR,
  data_collection_update_date DATETIME -- Date value,
  delete_ind BIT,
  delete_date DATETIME -- Date value,
  ord_nb_derived VARCHAR,
  bill_date DATE -- Date value
);

CREATE TABLE BillPayments (
  billpayment_id INT -- Unique identifier or primary key,
  payment_id VARCHAR -- Unique identifier or primary key,
  bill_id VARCHAR -- Unique identifier or primary key,
  paid_through_account_id VARCHAR -- Unique identifier or primary key,
  paid_through_account_name VARCHAR -- Unique identifier or primary key,
  amount DECIMAL -- Monetary amount,
  date DATE -- Date value,
  description VARCHAR -- Description or notes,
  payment_number VARCHAR -- Payment-related field
);

CREATE TABLE BillsOld (
  bill_id VARCHAR -- Unique identifier or primary key,
  vendor_id VARCHAR -- Unique identifier or primary key,
  vendor_name VARCHAR -- Name field,
  status VARCHAR,
  color_code VARCHAR,
  current_sub_status_id VARCHAR -- Unique identifier or primary key,
  current_sub_status VARCHAR,
  bill_number VARCHAR,
  reference_number VARCHAR -- Reference ID or external link,
  date DATE -- Date value,
  due_date DATE -- Date value,
  due_days VARCHAR,
  currency_id VARCHAR -- Unique identifier or primary key,
  currency_code VARCHAR -- Currency information,
  price_precision INT,
  exchange_rate DECIMAL -- Rate or percentage,
  total DECIMAL -- Total value,
  tds_total DECIMAL -- Total value,
  balance DECIMAL -- Remaining balance,
  unprocessed_payment_amount DECIMAL -- Monetary amount,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  attachment_name VARCHAR -- Name field,
  has_attachment BIT,
  is_uber_bill BIT,
  is_tally_bill BIT,
  cf_so VARCHAR,
  cf_so_unformatted VARCHAR,
  entity_type VARCHAR,
  client_viewed_time DATETIME,
  is_viewed_by_client BIT,
  is_bill_reconciliation_violated BIT,
  data_collection_update_date DATETIME -- Date value,
  delete_ind BIT,
  delete_date DATETIME -- Date value
);

CREATE TABLE BSLayOut (
  Layoutpk INT,
  Heading NVARCHAR,
  Subheading NVARCHAR,
  HeadingSort NVARCHAR,
  SubheadingSort NVARCHAR,
  DisplayDetail INT,
  Display Subheading INT
);

CREATE TABLE budget (
  account_pk INT,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  parent_account_id VARCHAR -- Unique identifier or primary key,
  jan_val DECIMAL,
  jan_notes TEXT,
  feb_val DECIMAL,
  feb_notes TEXT,
  mar_val DECIMAL,
  mar_notes TEXT,
  apr_val DECIMAL,
  apr_notes TEXT,
  may_val DECIMAL,
  may_notes TEXT,
  jun_val DECIMAL,
  jun_notes TEXT,
  jul_val DECIMAL,
  jul_notes TEXT,
  aug_val DECIMAL,
  aug_notes TEXT,
  sep_val DECIMAL,
  sep_notes TEXT,
  oct_val DECIMAL,
  oct_notes TEXT,
  nov_val DECIMAL,
  nov_notes TEXT,
  dec_val DECIMAL,
  dec_notes TEXT
);

CREATE TABLE budgetpivotview (
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  level_1_parent_name VARCHAR -- Name field,
  level_2_parent_name VARCHAR -- Name field,
  level_3_parent_name VARCHAR -- Name field,
  depth INT,
  displaylevel1 VARCHAR,
  displaylevel2 VARCHAR,
  displaylevel3 VARCHAR,
  displaylevel4 VARCHAR,
  sortcolbudget VARCHAR,
  jan_val DECIMAL,
  feb_val DECIMAL,
  mar_val DECIMAL,
  apr_val DECIMAL,
  may_val DECIMAL,
  jun_val DECIMAL,
  jul_val DECIMAL,
  aug_val DECIMAL,
  sep_val DECIMAL,
  oct_val DECIMAL,
  nov_val DECIMAL,
  dec_val DECIMAL
);

CREATE TABLE budgetUnpivotview (
  account_name VARCHAR -- Name field,
  level_1_parent_name VARCHAR -- Name field,
  level_2_parent_name VARCHAR -- Name field,
  level_3_parent_name VARCHAR -- Name field,
  depth INT,
  displaylevel1 VARCHAR,
  displaylevel2 VARCHAR,
  displaylevel3 VARCHAR,
  displaylevel4 VARCHAR,
  sortcolbudget VARCHAR,
  month_name NVARCHAR -- Name field,
  month_value DECIMAL
);

CREATE TABLE BudgetWithSubtotals (
  account_name VARCHAR -- Name field,
  displaylevel1 VARCHAR,
  displaylevel2 VARCHAR,
  displaylevel3 VARCHAR,
  displaylevel4 VARCHAR,
  sortcolbudget VARCHAR,
  StartOfMonth DATE,
  amount DECIMAL -- Monetary amount
);

CREATE TABLE BugetPivot (
  account_pk INT,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  parent_account_id VARCHAR -- Unique identifier or primary key,
  Val DECIMAL,
  month VARCHAR
);

CREATE TABLE CashflowAPView (
  status VARCHAR,
  vendor_name VARCHAR -- Name field,
  bill_id VARCHAR -- Unique identifier or primary key,
  bill_number VARCHAR,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  description VARCHAR -- Description or notes,
  cf_due_amount_1 DECIMAL -- Monetary amount,
  cf_due_amount_2 DECIMAL -- Monetary amount,
  cf_due_amount_3 DECIMAL -- Monetary amount,
  cf_due_amount_4 DECIMAL -- Monetary amount,
  reference_number VARCHAR -- Reference ID or external link,
  due_date DATE -- Date value,
  cf_due_date_2 DATE -- Date value,
  cf_due_date_3 DATE -- Date value,
  cf_due_date_4 DATE -- Date value,
  balance DECIMAL -- Remaining balance,
  total DECIMAL -- Total value,
  disfordisplay VARCHAR,
  item_total INT -- Total value,
  calcaccounttype VARCHAR,
  Amountdue DECIMAL -- Monetary amount,
  AmountThisWeek DECIMAL -- Monetary amount,
  AmountNextWeek DECIMAL -- Monetary amount,
  Outofscope DECIMAL
);

CREATE TABLE cashflowestimates (
  EstimateID INT -- Unique identifier or primary key,
  EstimateName VARCHAR -- Name field,
  EstimateAmount DECIMAL -- Monetary amount,
  PayDate DATE -- Date value,
  Frequency VARCHAR
);

CREATE TABLE CashFlowLayout (
  SortOrder INT,
  plsubheading VARCHAR,
  Details INT,
  plheading VARCHAR,
  plheadingSort INT,
  Plsubheaddispaly VARCHAR
);

CREATE TABLE cashflowwithROview (
  account_head VARCHAR,
  account_subhead VARCHAR,
  weeknum VARCHAR,
  Amount FLOAT -- Monetary amount
);

CREATE TABLE cfarview (
  invoice_id VARCHAR -- Unique identifier or primary key,
  invoice_number VARCHAR -- Invoice-related field,
  reference_number VARCHAR -- Reference ID or external link,
  customer_id VARCHAR -- Unique identifier or primary key,
  customer_name VARCHAR -- Name field,
  date DATE -- Date value,
  status VARCHAR,
  total DECIMAL -- Total value,
  balance DECIMAL -- Remaining balance,
  cf_amount_due_1 DECIMAL -- Monetary amount,
  cf_amount_due_2 DECIMAL -- Monetary amount,
  due_date DATE -- Date value,
  cf_due_date_2 DATE -- Date value,
  age INT,
  FirstMailDrop DATETIME,
  Amountdue DECIMAL -- Monetary amount,
  Duethisweek DECIMAL,
  Duenextweek DECIMAL,
  outofscope DECIMAL
);

CREATE TABLE ChartOfAccounts (
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  account_code VARCHAR,
  account_type VARCHAR,
  is_user_created BIT -- Record creation time,
  is_system_account BIT,
  is_standalone_account BIT,
  is_active BIT,
  can_show_in_ze BIT,
  is_involved_in_transaction BIT,
  current_balance DECIMAL -- Remaining balance,
  parent_account_id VARCHAR -- Unique identifier or primary key,
  parent_account_name VARCHAR -- Name field,
  depth VARCHAR,
  has_attachment BIT,
  is_child_present VARCHAR,
  child_count INT,
  documents TEXT,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  delete_ind BIT,
  general_account_type VARCHAR,
  data_collection_update_date DATETIME -- Date value,
  is_active_change_date DATE -- Date value
);

CREATE TABLE CommissionCalculations (
  Sales_Order VARCHAR,
  First_Mail_Drop DATE,
  Customer_Id VARCHAR -- Unique identifier or primary key,
  Status VARCHAR,
  TeamMemberName VARCHAR -- Name field,
  Rate DECIMAL -- Rate or percentage,
  Total_Revenue DECIMAL -- Total value,
  Total_COGS DECIMAL -- Total value,
  Net_Income DECIMAL,
  Commission DECIMAL,
  CommCalculated BIT,
  reviewCommCalc BIT,
  LastUpdatedDate DATETIME -- Date value
);

CREATE TABLE Contacts (
  contact_pk INT,
  contact_id BIGINT -- Unique identifier or primary key,
  contact_name VARCHAR -- Name field,
  company_name VARCHAR -- Name field,
  contact_type VARCHAR,
  status VARCHAR,
  payment_terms INT -- Payment-related field,
  payment_terms_label VARCHAR -- Payment-related field,
  currency_id BIGINT -- Unique identifier or primary key,
  currency_code VARCHAR -- Currency information,
  outstanding_receivable_amount DECIMAL -- Monetary amount,
  unused_credits_receivable_amount DECIMAL -- Monetary amount,
  first_name VARCHAR -- Name field,
  last_name VARCHAR -- Name field,
  email VARCHAR -- Email address,
  phone VARCHAR -- Phone number,
  mobile VARCHAR,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  delete_ind BIT,
  delete_date DATE -- Date value,
  data_collection_update_date DATETIME -- Date value
);

CREATE TABLE CreditNoteLineItems (
  creditnoteline_pk INT,
  item_id VARCHAR -- Unique identifier or primary key,
  line_item_id VARCHAR -- Unique identifier or primary key,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  name VARCHAR -- Name field,
  description VARCHAR -- Description or notes,
  invoice_id VARCHAR -- Unique identifier or primary key,
  invoice_item_id VARCHAR -- Unique identifier or primary key,
  creditnote_id VARCHAR -- Unique identifier or primary key,
  item_total DECIMAL -- Total value
);

CREATE TABLE creditnotes (
  id INT -- Unique identifier or primary key,
  creditnote_id VARCHAR -- Unique identifier or primary key,
  creditnote_number VARCHAR,
  status VARCHAR,
  reference_number VARCHAR -- Reference ID or external link,
  date DATE -- Date value,
  total DECIMAL -- Total value,
  balance DECIMAL -- Remaining balance,
  customer_id VARCHAR -- Unique identifier or primary key,
  customer_name VARCHAR -- Name field,
  currency_id VARCHAR -- Unique identifier or primary key,
  currency_code VARCHAR -- Currency information,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  is_emailed BIT -- Email address,
  delete_in BIT,
  delete_date DATETIME -- Date value,
  data_collection_update_date DATETIME -- Date value
);

CREATE TABLE customer (
  CustomerName VARCHAR -- Name field,
  zohoCustomerID VARCHAR -- Unique identifier or primary key,
  lob VARCHAR,
  rrCustomerID INT -- Unique identifier or primary key,
  zohocustomername VARCHAR -- Name field,
  rrcustomername VARCHAR -- Name field
);

CREATE TABLE CustomerPayments (
  payment_id BIGINT -- Unique identifier or primary key,
  payment_number INT -- Payment-related field,
  retainerinvoice_id VARCHAR -- Unique identifier or primary key,
  invoice_numbers VARCHAR -- Invoice-related field,
  date DATE -- Date value,
  payment_mode VARCHAR -- Payment-related field,
  payment_mode_formatted VARCHAR -- Payment-related field,
  amount DECIMAL -- Monetary amount,
  bcy_amount DECIMAL -- Monetary amount,
  unused_amount DECIMAL -- Monetary amount,
  bcy_unused_amount DECIMAL -- Monetary amount,
  account_id BIGINT -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  description TEXT -- Description or notes,
  reference_number VARCHAR -- Reference ID or external link,
  customer_id BIGINT -- Unique identifier or primary key,
  customer_name VARCHAR -- Name field,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  last_four_digits VARCHAR,
  gateway_transaction_id VARCHAR -- Unique identifier or primary key,
  payment_gateway VARCHAR -- Payment-related field,
  bcy_refunded_amount DECIMAL -- Monetary amount,
  applied_invoices TEXT -- Invoice-related field,
  has_attachment BIT,
  documents TEXT,
  custom_fields_list TEXT,
  tax_account_id VARCHAR -- Unique identifier or primary key,
  tax_account_name VARCHAR -- Name field,
  tax_amount_withheld DECIMAL -- Monetary amount,
  payment_type VARCHAR -- Payment-related field,
  payment_status VARCHAR -- Payment-related field,
  settlement_status VARCHAR,
  delete_ind BIT,
  data_collection_update_date DATETIME -- Date value,
  customer_advance_account_id VARCHAR -- Unique identifier or primary key,
  customer_advance_account_name VARCHAR -- Name field
);

CREATE TABLE Employee (
  EmployeeID INT -- Unique identifier or primary key,
  EmployeeName NVARCHAR -- Name field,
  Role NVARCHAR
);

CREATE TABLE esopbudget (
  account_pk INT,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  parent_account_id VARCHAR -- Unique identifier or primary key,
  jan_val DECIMAL,
  jan_notes TEXT,
  feb_val DECIMAL,
  feb_notes TEXT,
  mar_val DECIMAL,
  mar_notes TEXT,
  apr_val DECIMAL,
  apr_notes TEXT,
  may_val DECIMAL,
  may_notes TEXT,
  jun_val DECIMAL,
  jun_notes TEXT,
  jul_val DECIMAL,
  jul_notes TEXT,
  aug_val DECIMAL,
  aug_notes TEXT,
  sep_val DECIMAL,
  sep_notes TEXT,
  oct_val DECIMAL,
  oct_notes TEXT,
  nov_val DECIMAL,
  nov_notes TEXT,
  dec_val DECIMAL,
  dec_notes TEXT
);

CREATE TABLE esopbudgetpivotview (
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  level_1_parent_name VARCHAR -- Name field,
  level_2_parent_name VARCHAR -- Name field,
  level_3_parent_name VARCHAR -- Name field,
  depth INT,
  displaylevel1 VARCHAR,
  displaylevel2 VARCHAR,
  displaylevel3 VARCHAR,
  displaylevel4 VARCHAR,
  sortcolbudget VARCHAR,
  jan_val DECIMAL,
  feb_val DECIMAL,
  mar_val DECIMAL,
  apr_val DECIMAL,
  may_val DECIMAL,
  jun_val DECIMAL,
  jul_val DECIMAL,
  aug_val DECIMAL,
  sep_val DECIMAL,
  oct_val DECIMAL,
  nov_val DECIMAL,
  dec_val DECIMAL
);

CREATE TABLE esopbudgetUnpivotview (
  account_name VARCHAR -- Name field,
  level_1_parent_name VARCHAR -- Name field,
  level_2_parent_name VARCHAR -- Name field,
  level_3_parent_name VARCHAR -- Name field,
  depth INT,
  displaylevel1 VARCHAR,
  displaylevel2 VARCHAR,
  displaylevel3 VARCHAR,
  displaylevel4 VARCHAR,
  sortcolbudget VARCHAR,
  month_name NVARCHAR -- Name field,
  month_value DECIMAL
);

CREATE TABLE EsopBudgetWithSubtotals (
  account_name VARCHAR -- Name field,
  displaylevel1 VARCHAR,
  displaylevel2 VARCHAR,
  displaylevel3 VARCHAR,
  displaylevel4 VARCHAR,
  sortcolbudget VARCHAR,
  StartOfMonth DATE,
  amount DECIMAL -- Monetary amount
);

CREATE TABLE ExpenseLineItems (
  line_item_pk INT,
  line_item_id VARCHAR -- Unique identifier or primary key,
  expense_id VARCHAR -- Unique identifier or primary key,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  description VARCHAR -- Description or notes,
  item_total DECIMAL -- Total value,
  amount DECIMAL -- Monetary amount
);

CREATE TABLE expenses (
  expense_id BIGINT -- Unique identifier or primary key,
  date DATE -- Date value,
  user_name VARCHAR -- Name field,
  paid_through_account_name VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  description TEXT -- Description or notes,
  currency_id BIGINT -- Unique identifier or primary key,
  currency_code VARCHAR -- Currency information,
  bcy_total DECIMAL -- Total value,
  bcy_total_without_tax DECIMAL -- Total value,
  total DECIMAL -- Total value,
  total_without_tax DECIMAL -- Total value,
  is_billable BIT,
  reference_number VARCHAR -- Reference ID or external link,
  customer_id VARCHAR -- Unique identifier or primary key,
  is_personal BIT,
  customer_name VARCHAR -- Name field,
  vendor_id VARCHAR -- Unique identifier or primary key,
  vendor_name VARCHAR -- Name field,
  status VARCHAR,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  expense_receipt_name VARCHAR -- Name field,
  exchange_rate DECIMAL -- Rate or percentage,
  distance DECIMAL,
  mileage_rate DECIMAL -- Rate or percentage,
  mileage_unit VARCHAR,
  mileage_type VARCHAR,
  expense_type VARCHAR,
  report_id VARCHAR -- Unique identifier or primary key,
  start_reading DECIMAL,
  end_reading DECIMAL,
  report_name VARCHAR -- Name field,
  report_number VARCHAR,
  has_attachment BIT,
  custom_fields_list TEXT,
  data_collection_update_date DATETIME -- Date value,
  delete_ind BIT,
  delete_date DATETIME -- Date value,
  paid_through_account_id VARCHAR -- Unique identifier or primary key
);

CREATE TABLE gptable (
  salesorder_id VARCHAR -- Unique identifier or primary key,
  customer_name VARCHAR -- Name field,
  customer_id VARCHAR -- Unique identifier or primary key,
  salesorder_number VARCHAR,
  AccrualMonth DATETIME,
  reference_number VARCHAR -- Reference ID or external link,
  date DATE -- Date value,
  total DECIMAL -- Total value,
  bcy_total DECIMAL -- Total value,
  total_invoiced_amount DECIMAL -- Monetary amount,
  creditnotesamount DECIMAL -- Monetary amount,
  last_modified_time DATETIME -- Last modification time,
  quantity_invoiced DECIMAL -- Invoice-related field,
  order_status VARCHAR,
  invoiced_status VARCHAR -- Invoice-related field,
  paid_status VARCHAR -- Unique identifier or primary key,
  status VARCHAR,
  salesperson_name VARCHAR -- Name field,
  cf_cycle VARCHAR,
  delete_ind BIT,
  data_collection_update_date DATETIME -- Date value,
  Cyclenumber FLOAT,
  volume INT,
  Digitalflag NVARCHAR,
  postagebills DECIMAL,
  prodbills DECIMAL,
  databills DECIMAL,
  otherbills DECIMAL,
  marketingbills DECIMAL,
  salescommissions DECIMAL,
  LS1COGS DECIMAL
);

CREATE TABLE invoicelineitems (
  line_item_pk INT,
  invoice_id VARCHAR -- Unique identifier or primary key,
  line_item_id VARCHAR -- Unique identifier or primary key,
  item_id VARCHAR -- Unique identifier or primary key,
  sku VARCHAR -- Stock keeping unit,
  item_order INT,
  name VARCHAR -- Name field,
  internal_name VARCHAR -- Name field,
  description TEXT -- Description or notes,
  unit VARCHAR,
  quantity INT -- Quantity or count,
  discount DECIMAL,
  discounts TEXT,
  bcy_rate DECIMAL -- Rate or percentage,
  rate DECIMAL -- Rate or percentage,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  item_total DECIMAL -- Total value,
  bill_id VARCHAR -- Unique identifier or primary key,
  bill_item_id VARCHAR -- Unique identifier or primary key,
  project_id VARCHAR -- Unique identifier or primary key,
  expense_id VARCHAR -- Unique identifier or primary key,
  item_type VARCHAR,
  salesorder_item_id VARCHAR -- Unique identifier or primary key,
  cost_amount DECIMAL -- Monetary amount,
  markup_percent DECIMAL,
  ord_nb_derived VARCHAR,
  invoice_date DATE -- Date value,
  delete_ind BIT,
  data_collection_update_date DATETIME -- Date value,
  custom_fields TEXT,
  tags TEXT,
  documents TEXT,
  salesperson_name VARCHAR -- Name field,
  customer_name VARCHAR -- Name field,
  company_name VARCHAR -- Name field,
  status VARCHAR,
  reference_number VARCHAR -- Reference ID or external link,
  email VARCHAR -- Email address,
  created_by VARCHAR -- Record creation time,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  updated_time DATETIME -- Date value,
  is_viewed_by_client BIT,
  is_emailed BIT -- Email address,
  mail_first_viewed_time DATETIME,
  mail_last_viewed_time DATETIME,
  currency_code VARCHAR -- Currency information,
  currency_symbol VARCHAR -- Currency information,
  template_type VARCHAR,
  invoice_url TEXT -- Invoice-related field,
  transaction_type VARCHAR,
  reminders_sent INT,
  last_reminder_sent_date DATETIME -- Date value,
  last_payment_date DATETIME -- Date value,
  template_id VARCHAR -- Unique identifier or primary key,
  write_off_amount DECIMAL -- Monetary amount,
  exchange_rate DECIMAL -- Rate or percentage,
  unprocessed_payment_amount DECIMAL -- Monetary amount
);

CREATE TABLE InvoicePayments (
  InvoicePayment_pk INT -- Invoice-related field,
  invoice_payment_id VARCHAR -- Unique identifier or primary key,
  Invoice_id VARCHAR -- Unique identifier or primary key,
  Payment_id VARCHAR -- Unique identifier or primary key,
  date DATE -- Date value,
  payment_mode VARCHAR -- Payment-related field,
  reference_number VARCHAR -- Reference ID or external link,
  description VARCHAR -- Description or notes,
  amount DECIMAL -- Monetary amount
);

CREATE TABLE Invoices (
  invoice_id VARCHAR -- Unique identifier or primary key,
  ach_payment_initiated VARCHAR -- Payment-related field,
  zcrm_potential_id VARCHAR -- Unique identifier or primary key,
  customer_id VARCHAR -- Unique identifier or primary key,
  zcrm_potential_name VARCHAR -- Name field,
  customer_name VARCHAR -- Name field,
  company_name VARCHAR -- Name field,
  status VARCHAR,
  invoice_number VARCHAR -- Invoice-related field,
  reference_number VARCHAR -- Reference ID or external link,
  date DATE -- Date value,
  due_date DATE -- Date value,
  due_days VARCHAR,
  email VARCHAR -- Email address,
  project_name VARCHAR -- Name field,
  country VARCHAR,
  phone VARCHAR -- Phone number,
  created_by VARCHAR -- Record creation time,
  total DECIMAL -- Total value,
  balance DECIMAL -- Remaining balance,
  payment_expected_date DATE -- Date value,
  custom_fields TEXT,
  custom_field_hash TEXT,
  tags TEXT,
  salesperson_name VARCHAR -- Name field,
  shipping_charge DECIMAL,
  adjustment DECIMAL,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  updated_time DATETIME -- Date value,
  is_viewed_by_client VARCHAR,
  has_attachment VARCHAR,
  client_viewed_time DATETIME,
  is_viewed_in_mail VARCHAR,
  is_emailed VARCHAR -- Email address,
  mail_first_viewed_time DATE,
  mail_last_viewed_time DATE,
  color_code VARCHAR,
  current_sub_status_id VARCHAR -- Unique identifier or primary key,
  current_sub_status VARCHAR,
  currency_id VARCHAR -- Unique identifier or primary key,
  schedule_time VARCHAR,
  currency_code VARCHAR -- Currency information,
  currency_symbol VARCHAR -- Currency information,
  template_type VARCHAR,
  invoice_url VARCHAR -- Invoice-related field,
  transaction_type VARCHAR,
  reminders_sent INT,
  last_reminder_sent_date DATE -- Date value,
  last_payment_date DATE -- Date value,
  template_id VARCHAR -- Unique identifier or primary key,
  documents TEXT,
  salesperson_id VARCHAR -- Unique identifier or primary key,
  write_off_amount DECIMAL -- Monetary amount,
  exchange_rate DECIMAL -- Rate or percentage,
  unprocessed_payment_amount DECIMAL -- Monetary amount,
  billing_address VARCHAR -- Address info,
  billing_street2 VARCHAR,
  billing_city VARCHAR,
  billing_state VARCHAR,
  billing_zipcode VARCHAR,
  billing_country VARCHAR,
  billing_phone VARCHAR -- Phone number,
  billing_fax VARCHAR,
  billing_attention VARCHAR,
  shipping_address VARCHAR -- Address info,
  shipping_street2 VARCHAR,
  shipping_city VARCHAR,
  shipping_state VARCHAR,
  shipping_zipcode VARCHAR,
  shipping_country VARCHAR,
  shipping_phone VARCHAR -- Phone number,
  shipping_fax VARCHAR,
  shipping_attention VARCHAR,
  delete_ind BIT,
  data_collection_update_date DATETIME -- Date value,
  cf_amount_due_1 DECIMAL -- Monetary amount,
  cf_due_date_2 DATE -- Date value,
  cf_amount_due_2 DECIMAL -- Monetary amount
);

CREATE TABLE INVOICESSSIVIEW (
  invoice_id VARCHAR -- Unique identifier or primary key,
  status VARCHAR,
  reference_number VARCHAR -- Reference ID or external link,
  invoice_number VARCHAR -- Invoice-related field,
  date DATE -- Date value,
  due_date DATE -- Date value,
  due_days VARCHAR,
  email VARCHAR -- Email address,
  country VARCHAR,
  created_by VARCHAR -- Record creation time,
  total DECIMAL -- Total value,
  balance DECIMAL -- Remaining balance,
  custom_field_hash TEXT,
  adjustment DECIMAL,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  is_viewed_by_client VARCHAR,
  has_attachment VARCHAR,
  client_viewed_time DATETIME,
  current_sub_status_id VARCHAR -- Unique identifier or primary key,
  current_sub_status VARCHAR,
  transaction_type VARCHAR,
  last_reminder_sent_date DATE -- Date value,
  last_payment_date DATE -- Date value,
  salesperson_id VARCHAR -- Unique identifier or primary key,
  exchange_rate DECIMAL -- Rate or percentage,
  unprocessed_payment_amount DECIMAL -- Monetary amount,
  delete_ind BIT,
  data_collection_update_date DATETIME -- Date value,
  cf_amount_due_1 DECIMAL -- Monetary amount,
  cf_due_date_2 DATE -- Date value,
  cf_amount_due_2 DECIMAL -- Monetary amount
);

CREATE TABLE JournalLineItems (
  line_item_pk INT,
  line_item_id VARCHAR -- Unique identifier or primary key,
  journal_id VARCHAR -- Unique identifier or primary key,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  description VARCHAR -- Description or notes,
  item_total DECIMAL -- Total value,
  debit_or_credit VARCHAR,
  amount DECIMAL -- Monetary amount
);

CREATE TABLE journals (
  journal_id BIGINT -- Unique identifier or primary key,
  journal_date DATE -- Date value,
  entry_number INT,
  reference_number VARCHAR -- Reference ID or external link,
  currency_id BIGINT -- Unique identifier or primary key,
  status VARCHAR,
  notes TEXT,
  journal_type VARCHAR,
  entity_type VARCHAR,
  total DECIMAL -- Total value,
  bcy_total DECIMAL -- Total value,
  created_by_id BIGINT -- Unique identifier or primary key,
  created_by_name VARCHAR -- Name field,
  delete_ind BIT,
  data_collection_update_date DATETIME -- Date value
);

CREATE TABLE LS1_Rate (
  id INT -- Unique identifier or primary key,
  date DATE -- Date value,
  amount DECIMAL -- Monetary amount
);

CREATE TABLE NWCLayout (
  ID INT -- Unique identifier or primary key,
  Heading NVARCHAR,
  Subheading NVARCHAR,
  HeadingSort INT,
  SubheadingSort CHAR,
  DisplayDetail INT
);

CREATE TABLE openingbalance (
  id INT -- Unique identifier or primary key,
  opening_balance_id VARCHAR -- Unique identifier or primary key,
  date DATE -- Date value,
  price_precision INT,
  account_split_id VARCHAR -- Unique identifier or primary key,
  account_id VARCHAR -- Unique identifier or primary key,
  account_name VARCHAR -- Name field,
  debit_or_credit VARCHAR,
  exchange_rate DECIMAL -- Rate or percentage,
  currency_id VARCHAR -- Unique identifier or primary key,
  currency_code VARCHAR -- Currency information,
  bcy_amount DECIMAL -- Monetary amount,
  amount DECIMAL -- Monetary amount,
  total_obid DECIMAL -- Unique identifier or primary key,
  data_collection_date DATE -- Date value
);

CREATE TABLE PandLLedgerView (
  ParentAccountId VARCHAR -- Unique identifier or primary key,
  Account_Name VARCHAR -- Name field,
  Amount DECIMAL -- Monetary amount,
  Account_id VARCHAR -- Unique identifier or primary key,
  ParentAccountName VARCHAR -- Name field,
  Month INT,
  Year INT,
  StartOfMonth DATE,
  date DATE -- Date value,
  SortCol VARCHAR,
  account_type VARCHAR,
  SortOrder INT,
  plheading VARCHAR,
  plsubheading VARCHAR
);

CREATE TABLE PandLView (
  ParentAccountId VARCHAR -- Unique identifier or primary key,
  Account_Name VARCHAR -- Name field,
  Amount DECIMAL -- Monetary amount,
  Account_id VARCHAR -- Unique identifier or primary key,
  ParentAccountName VARCHAR -- Name field,
  Month INT,
  Year INT,
  StartOfMonth DATE,
  SortCol VARCHAR,
  account_type VARCHAR,
  SortOrder INT,
  plheading VARCHAR,
  plsubheading VARCHAR
);

CREATE TABLE Pandlviewwithsubtotals (
  ParentAccountName VARCHAR -- Name field,
  Account_Name VARCHAR -- Name field,
  StartOfMonth DATE,
  SortCol VARCHAR,
  SortOrder INT,
  plsubheading VARCHAR,
  amount DECIMAL -- Monetary amount
);

CREATE TABLE payrolldate (
  Monthnumber INT,
  date DATE -- Date value,
  type VARCHAR,
  bonus_ind INT
);

CREATE TABLE Rate (
  ID INT -- Unique identifier or primary key,
  CustomerName NVARCHAR -- Name field,
  rrCustomerID BIGINT -- Unique identifier or primary key,
  zohoCustomerID VARCHAR -- Unique identifier or primary key,
  TeamMemberName NVARCHAR -- Name field,
  TeamMemberRole NVARCHAR,
  teammemberid INT -- Unique identifier or primary key,
  Month DATE,
  Year INT,
  Rate DECIMAL -- Rate or percentage,
  LOB VARCHAR,
  SOnumber VARCHAR
);

CREATE TABLE RateNew (
  ID INT -- Unique identifier or primary key,
  CustomerName NVARCHAR -- Name field,
  rrCustomerID BIGINT -- Unique identifier or primary key,
  zohoCustomerID VARCHAR -- Unique identifier or primary key,
  TeamMemberName NVARCHAR -- Name field,
  TeamMemberRole NVARCHAR,
  teammemberid INT -- Unique identifier or primary key,
  Month DATE,
  Year INT,
  Rate DECIMAL -- Rate or percentage,
  LOB VARCHAR,
  SOnumber VARCHAR
);

CREATE TABLE RateNew2 (
  ID INT -- Unique identifier or primary key,
  CustomerName NVARCHAR -- Name field,
  rrCustomerID BIGINT -- Unique identifier or primary key,
  zohoCustomerID VARCHAR -- Unique identifier or primary key,
  TeamMemberName NVARCHAR -- Name field,
  TeamMemberRole NVARCHAR,
  teammemberid INT -- Unique identifier or primary key,
  Month DATE,
  Year INT,
  Rate DECIMAL -- Rate or percentage,
  LOB VARCHAR,
  SOnumber VARCHAR
);

CREATE TABLE retainerinvoices (
  retainerinvoice_id VARCHAR -- Unique identifier or primary key,
  customer_name VARCHAR -- Name field,
  retainerinvoice_number VARCHAR -- Invoice-related field,
  customer_id VARCHAR -- Unique identifier or primary key,
  status VARCHAR,
  reference_number VARCHAR -- Reference ID or external link,
  project_or_estimate_name VARCHAR -- Name field,
  date DATE -- Date value,
  currency_id VARCHAR -- Unique identifier or primary key,
  currency_code VARCHAR -- Currency information,
  is_viewed_by_client BIT,
  client_viewed_time DATETIME,
  total DECIMAL -- Total value,
  balance DECIMAL -- Remaining balance,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  is_emailed BIT -- Email address,
  last_payment_date DATE -- Date value,
  has_attachment BIT,
  data_collection_update_date DATETIME -- Date value,
  color_code VARCHAR,
  current_sub_status_id VARCHAR -- Unique identifier or primary key,
  current_sub_status VARCHAR,
  mail_first_viewed_time DATETIME,
  mail_last_viewed_time DATETIME,
  cf_due_date DATE -- Date value,
  cf_108943000002628019 VARCHAR,
  delete_ind BIT,
  delete_date DATETIME -- Date value
);

CREATE TABLE rr_Campaigns (
  SalesOrder_Id INT -- Unique identifier or primary key,
  Client_Id INT -- Unique identifier or primary key,
  Product_Id INT -- Unique identifier or primary key,
  Sales_Order NVARCHAR,
  Client_Name NVARCHAR -- Name field,
  Product NVARCHAR,
  Description NVARCHAR -- Description or notes,
  Cycle_Number FLOAT,
  Num_of_Schedule_Items INT,
  Volume INT,
  Num_of_Campaign_Business_Processes INT,
  Method NVARCHAR,
  Revenue_Accrual_Month NVARCHAR,
  First_Mail_Drop DATETIME,
  Gross_Profit_Pct FLOAT
);

CREATE TABLE rr_Clients (
  Client_id INT -- Unique identifier or primary key,
  Color_Display NVARCHAR,
  Name NVARCHAR -- Name field,
  Number_Of_Campaigns INT,
  Line_Of_Business NVARCHAR,
  LOB_Ids NVARCHAR -- Unique identifier or primary key
);

CREATE TABLE rr_COGS (
  Record_ID# INT -- Unique identifier or primary key,
  Date_Created DATETIME -- Date value,
  SalesOrder_Id INT -- Unique identifier or primary key,
  Campaign_Client_Name NVARCHAR -- Name field,
  Campaign_Cycle_Number FLOAT,
  Campaign_Sales_Order NVARCHAR,
  Campaign_Client_Cycle_#_Description NVARCHAR -- Description or notes,
  Category NVARCHAR,
  Description NVARCHAR -- Description or notes,
  Type NVARCHAR,
  Cost FLOAT,
  Quantity INT -- Quantity or count,
  Projected_Expense FLOAT -- Related to project
);

CREATE TABLE rr_HolidayGroups (
  Weekday BIT,
  Number_of_Holiday_Records INT -- Unique identifier or primary key,
  Multiple_Days NVARCHAR,
  Maximum_Date_Observed DATE -- Date value,
  Name NVARCHAR -- Name field,
  Initial_Holiday_Date DATE -- Unique identifier or primary key
);

CREATE TABLE rr_Holidays (
  Holiday_Id INT -- Unique identifier or primary key,
  Name NVARCHAR -- Name field,
  Date_Observed DATE -- Date value,
  Weekday BIT
);

CREATE TABLE rr_LinesOfBusiness (
  LOB_Id INT -- Unique identifier or primary key,
  Name NVARCHAR -- Name field
);

CREATE TABLE rr_Products (
  Product_Id INT -- Unique identifier or primary key,
  Name NVARCHAR -- Name field
);

CREATE TABLE rr_Revenue (
  Date_Created DATETIME -- Date value,
  Projected_Revenue FLOAT -- Related to project,
  Description NVARCHAR -- Description or notes,
  Type NVARCHAR,
  Quantity INT -- Quantity or count,
  Cost FLOAT,
  Descriptor NVARCHAR,
  Delete_Orphan VARCHAR,
  FQ:_Check_Proceeding_Campaigns_same_Revenue NVARCHAR,
  Apply_This_new_Revenue_to_Proceeding_Campaigns? NVARCHAR
);

CREATE TABLE rr_Schedule (
  Name VARCHAR -- Name field,
  Roadmap_Client_Name VARCHAR -- Name field,
  Campaign_Description VARCHAR -- Description or notes,
  Order INT,
  Duration INT,
  Lead_Time INT,
  Calculation_Type VARCHAR,
  Calculation_Direction VARCHAR,
  Planned_Start DATETIME,
  Planned_End DATETIME,
  Stakeholders VARCHAR,
  Stakeholder_Groups VARCHAR,
  Num_of_Child_Schedule_Item_Records INT,
  Planned_Start_ps DATETIME,
  Planned_Start_firstdayofweek_peb DATETIME,
  Planned_Start_forward_h DATETIME,
  Planned_Start_forward_firstdayofweek_hd DATETIME,
  Name_Date VARCHAR -- Name field,
  Summary_Header_Copy VARCHAR
);

CREATE TABLE rr_StakeholderGroups (
  StakeholderGroup_Id INT -- Unique identifier or primary key,
  Name NVARCHAR -- Name field,
  Num_of_Stakeholders INT
);

CREATE TABLE rr_Stakeholders (
  Stakeholder_Id INT -- Unique identifier or primary key,
  Full_Name NVARCHAR -- Name field,
  StakeholderGroup_Id INT -- Unique identifier or primary key,
  Stakeholder_Group_Name NVARCHAR -- Name field,
  QB_User NVARCHAR,
  Vendor_Product_Records NVARCHAR -- Related to vendor,
  Add_Vendor_Product NVARCHAR -- Related to vendor,
  Vendor_Product_Cost_Records NVARCHAR -- Related to vendor,
  Add_Vendor_Product_Cost NVARCHAR -- Related to vendor
);

CREATE TABLE rr_VendorProductCost (
  Cost_Id INT -- Unique identifier or primary key,
  Product_Id INT -- Unique identifier or primary key,
  High DECIMAL,
  Low DECIMAL,
  Base_Price DECIMAL,
  Add_On_1 NVARCHAR,
  Add_On_1_Cost DECIMAL,
  Add_On_2 NVARCHAR,
  Add_On_2_Cost DECIMAL,
  Add_On_3 NVARCHAR,
  Add_On_3_Cost DECIMAL,
  Add_On_4 NVARCHAR,
  Add_On_4_Cost DECIMAL,
  Add_On_5 NVARCHAR,
  Add_On_5_Cost DECIMAL,
  Total_Cost DECIMAL -- Total value,
  VendorProduct_Product NVARCHAR -- Related to vendor
);

CREATE TABLE rr_VendorProducts (
  Product_Id INT -- Unique identifier or primary key,
  Product NVARCHAR,
  Stakeholder_QB_User NVARCHAR,
  Attachment_Records NVARCHAR,
  Add_Attachment NVARCHAR,
  Vendor_Product_Cost_Records NVARCHAR -- Related to vendor,
  Add_Vendor_Product_Cost NVARCHAR -- Related to vendor
);

CREATE TABLE salesorders (
  salesorder_id VARCHAR -- Unique identifier or primary key,
  zcrm_potential_id VARCHAR -- Unique identifier or primary key,
  zcrm_potential_name VARCHAR -- Name field,
  customer_name VARCHAR -- Name field,
  customer_id VARCHAR -- Unique identifier or primary key,
  email VARCHAR -- Email address,
  delivery_date DATE -- Date value,
  company_name VARCHAR -- Name field,
  color_code VARCHAR,
  current_sub_status_id VARCHAR -- Unique identifier or primary key,
  current_sub_status VARCHAR,
  pickup_location_id VARCHAR -- Unique identifier or primary key,
  salesorder_number VARCHAR,
  reference_number VARCHAR -- Reference ID or external link,
  date DATE -- Date value,
  shipment_date DATE -- Date value,
  shipment_days VARCHAR,
  due_in_days INT,
  currency_id VARCHAR -- Unique identifier or primary key,
  source VARCHAR,
  currency_code VARCHAR -- Currency information,
  total DECIMAL -- Total value,
  bcy_total DECIMAL -- Total value,
  total_invoiced_amount DECIMAL -- Monetary amount,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  is_emailed BIT -- Email address,
  quantity_invoiced DECIMAL -- Invoice-related field,
  order_status VARCHAR,
  invoiced_status VARCHAR -- Invoice-related field,
  paid_status VARCHAR -- Unique identifier or primary key,
  status VARCHAR,
  order_fulfillment_type VARCHAR,
  salesperson_name VARCHAR -- Name field,
  has_attachment BIT,
  cf_cycle VARCHAR,
  cf_cycle_unformatted VARCHAR,
  custom_fields_list TEXT,
  delivery_method VARCHAR,
  delivery_method_id VARCHAR -- Unique identifier or primary key,
  delete_ind BIT,
  data_collection_update_date DATETIME -- Date value
);

CREATE TABLE SSIRate (
  ID INT -- Unique identifier or primary key,
  zohoCustomerID VARCHAR -- Unique identifier or primary key,
  TeamMemberName NVARCHAR -- Name field,
  TeamMemberRole NVARCHAR,
  teammemberid INT -- Unique identifier or primary key,
  Rate DECIMAL -- Rate or percentage,
  LOB VARCHAR,
  InvoiceNumber VARCHAR -- Invoice-related field
);

CREATE TABLE sysdiagrams (
  name NVARCHAR -- Name field,
  principal_id INT -- Unique identifier or primary key,
  diagram_id INT -- Unique identifier or primary key,
  version INT,
  definition VARBINARY
);

CREATE TABLE Vendor_Product_Cost (
  Base_Price DECIMAL,
  Add_On_1 TEXT,
  Add_On_1_Cost DECIMAL,
  Add_On_2 TEXT,
  Add_On_2_Cost DECIMAL,
  Add_On_3 TEXT,
  Add_On_3_Cost DECIMAL,
  Add_On_4 TEXT,
  Add_On_4_Cost DECIMAL,
  Add_On_5 TEXT,
  Add_On_5_Cost DECIMAL,
  Total_Cost DECIMAL -- Total value,
  Vendor_Product TEXT -- Related to vendor,
  High INT,
  Low INT
);

CREATE TABLE VendorBillingLookup (
  Vendor VARCHAR -- Related to vendor,
  Days INT,
  Type VARCHAR
);

CREATE TABLE VendorCreditDetails (
  vendor_credit_pk INT -- Related to vendor,
  vendor_credit_id VARCHAR -- Unique identifier or primary key,
  vendor_credit_number VARCHAR -- Related to vendor,
  status VARCHAR,
  reference_number VARCHAR -- Reference ID or external link,
  date DATE -- Date value,
  sub_total DECIMAL -- Total value,
  total DECIMAL -- Total value,
  balance DECIMAL -- Remaining balance,
  notes VARCHAR,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  data_collection_update_date DATETIME -- Date value,
  delete_ind BIT,
  delete_date DATETIME -- Date value
);

CREATE TABLE VendorCreditLineItems (
  line_item_pk INT,
  vendor_credit_pk INT -- Related to vendor,
  line_item_id VARCHAR -- Unique identifier or primary key,
  vendor_credit_id VARCHAR -- Unique identifier or primary key,
  item_id VARCHAR -- Unique identifier or primary key,
  account_id VARCHAR -- Unique identifier or primary key,
  product_type VARCHAR,
  account_name VARCHAR -- Name field,
  name VARCHAR -- Name field,
  description VARCHAR -- Description or notes,
  quantity INT -- Quantity or count,
  unit VARCHAR,
  rate DECIMAL -- Rate or percentage,
  item_total DECIMAL -- Total value,
  tax_percentage DECIMAL,
  tax_name VARCHAR -- Name field,
  item_total_inclusive_of_tax DECIMAL -- Total value,
  hsn_or_sac VARCHAR,
  project_id VARCHAR -- Unique identifier or primary key,
  project_name VARCHAR -- Name field,
  delete_ind BIT,
  delete_date DATETIME -- Date value,
  ord_nb_derived VARCHAR,
  vendor_credit_date DATE -- Date value
);

CREATE TABLE VendorCreditsOld (
  vendor_credit_id VARCHAR -- Unique identifier or primary key,
  vendor_credit_number VARCHAR -- Related to vendor,
  status VARCHAR,
  reference_number VARCHAR -- Reference ID or external link,
  date DATE -- Date value,
  total DECIMAL -- Total value,
  balance DECIMAL -- Remaining balance,
  vendor_id VARCHAR -- Unique identifier or primary key,
  vendor_name VARCHAR -- Name field,
  currency_id VARCHAR -- Unique identifier or primary key,
  currency_code VARCHAR -- Currency information,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  has_attachment BIT,
  exchange_rate DECIMAL -- Rate or percentage,
  data_collection_update_date DATETIME -- Date value,
  delete_ind BIT,
  delete_date DATETIME -- Date value
);

CREATE TABLE VendorPayments (
  payment_id BIGINT -- Unique identifier or primary key,
  vendor_id BIGINT -- Unique identifier or primary key,
  currency_id BIGINT -- Unique identifier or primary key,
  status VARCHAR,
  currency_code VARCHAR -- Currency information,
  vendor_name VARCHAR -- Name field,
  payment_mode VARCHAR -- Payment-related field,
  payment_number INT -- Payment-related field,
  description TEXT -- Description or notes,
  date DATE -- Date value,
  reference_number VARCHAR -- Reference ID or external link,
  exchange_rate DECIMAL -- Rate or percentage,
  amount DECIMAL -- Monetary amount,
  bcy_amount DECIMAL -- Monetary amount,
  paid_through_account_id BIGINT -- Unique identifier or primary key,
  paid_through_account_name VARCHAR -- Unique identifier or primary key,
  balance DECIMAL -- Remaining balance,
  bcy_balance DECIMAL -- Remaining balance,
  created_time DATETIME -- Record creation time,
  last_modified_time DATETIME -- Last modification time,
  is_paid_via_print_check BIT -- Unique identifier or primary key,
  has_attachment BIT,
  is_ach_payment BIT -- Payment-related field,
  ach_payment_status VARCHAR -- Payment-related field,
  ach_gw_transaction_id VARCHAR -- Unique identifier or primary key,
  check_details TEXT,
  data_collection_update_date DATETIME -- Date value,
  delete_ind BIT,
  delete_date DATETIME -- Date value,
  offset_account_id VARCHAR -- Unique identifier or primary key,
  offset_account_name VARCHAR -- Name field,
  bill_numbers VARCHAR
);